apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-testing-multiple-components-long-name-7d7m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-testing-multiple-components-long-name-7d7m
    app.kubernetes.io/part-of: my-app-testing
  name: python-testing-multiple-components-long-name-7d7m
  namespace: rsoaresd-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: python-testing-multiple-components-long-name-7d7m
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: python-testing-multiple-components-long-name-7d7m
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:8J8em-python-testing-multiple-components-long-name-7d7m
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
