apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-testing-multiple-components-long-name-7d7m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-testing-multiple-components-long-name-7d7m
    app.kubernetes.io/part-of: my-app-testing
  name: python-testing-multiple-components-long-name-7d7m
  namespace: rsoaresd-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: python-testing-multiple-components-long-name-7d7m
    weight: null
status: {}
