apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: python-testing-multiple-components-long-name-7d7m
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: python-testing-multiple-components-long-name-7d7m
    app.kubernetes.io/part-of: my-app-testing
  name: python-testing-multiple-components-long-name-7d7m
  namespace: rsoaresd-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: python-testing-multiple-components-long-name-7d7m
status:
  loadBalancer: {}
