apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: python-testing-multiple-components-long-name-7d7m
  namespace: rsoaresd-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:35aa6cc136383007a22bb0c46b36d25343a6460abf4baa1790f2af09bcd639f4
        name: my-python
        resources: {}
status: {}
